version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173" # Expose the frontend service on port 5173 (Vite default)
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000" # Expose the backend service on port 8000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
